Repository codefori/vscode-ibmi, pull requests merged in 2023-10, with the labels that each got.

#1574 Split Object browser's Refresh in two separate actions
  package.json
  src/views/objectBrowser.ts
Labels: bug, enhancement

#1608 Add "RPGPPOPT(*LVL2)" by default to CRTSQLRPGI
  package.json
  src/api/local/LocalLanguageActions.ts
Labels: enhancement

#1612 Fixed sort action in Object Browser
  src/views/objectBrowser.ts
Labels: bug

#1595 Environment variable to manage debug settings
  package-lock.json
  package.json
  src/api/debug/index.ts
  src/webviews/settings/index.ts
Labels: build
