Repository codefori/vscode-ibmi, pull requests merged in 2023-11, with the labels that each got.

#1651 Look for member on SYSBAS if config.sourceASP is set
  src/api/IBMiContent.ts
Labels: bug

#1624 Added Refresh option to actions
  package.json
  src/api/CompileTools.ts
  src/instantiate.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/webviews/actions/index.ts
Labels: enhancement

#1659 Ignore stat error when no hidden files in directory
  src/api/IBMiContent.ts
Labels: bug

#1664 Add "Run on protected" option on Actions
  package.json
  src/api/CompileTools.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/webviews/actions/index.ts
Labels: enhancement

#1676 fix use of old vsce command
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
Labels: build

#1673 Sanitize library names before running liblist command
  src/api/CompileTools.ts
  src/api/IBMiContent.ts
  src/api/Tools.ts
  src/testing/content.ts
  src/testing/tools.ts
  src/views/LibraryListView.ts
Labels: bug
