Repository codefori/vscode-ibmi, pull requests merged in 2023-06, with the labels that each got.

#1327 Fix display of empty and non-existing directories
  src/api/IBMiContent.ts
  src/testing/connection.ts
  src/testing/content.ts
  src/views/ifsBrowser.js
Labels: bug

#1336 feat: Add Copy Path to IFS browser
  package.json
  src/views/ifsBrowser.js
Labels: enhancement

#1339 Check if member can be written before edition
  src/api/IBMiContent.ts
  src/instantiate.ts
  src/views/objectBrowser.js
Labels: enhancement

#1353 Always start a new terminal for Open Terminal Here
  src/instantiate.ts
Labels: bug

#1379 Fix Quick Connect remoteFeatures
  src/api/IBMi.ts
Labels: bug

#1328 Upgrade node-ssh to 13.1
  package-lock.json
  package.json
  webpack.config.js
Labels: build

#1402 Fix IFS shortcuts menu items order
  package.json
Labels: bug
