Repository codefori/vscode-ibmi, pull requests merged in 2023-12, with the labels that each got.

#1680 feat(Go to file): Autotype suggestions typing path
  src/instantiate.ts
Labels: enhancement

#1701 Fix goto file quickpick
  src/instantiate.ts
Labels: bug

#1700 IFS browser enhancements
  package.json
  src/views/ifsBrowser.ts
Labels: enhancement

#1703 Fixes/deployment_working_directory
  src/api/CompileTools.ts
  src/api/local/deployTools.ts
  src/api/local/deployment.ts
  src/views/ifsBrowser.ts
Labels: bug, build

#1708 Removed deprecated commands call and ignore library list
  src/api/CompileTools.ts
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/filesystems/qsys/extendedContent.ts
  src/languages/clle/clApi.ts
  src/languages/clle/getnewlibl.ts
  src/testing/content.ts
  src/typings.ts
  src/views/objectBrowser.ts
Labels: enhancement

#1695 Add /QOpenSys/pkgs/bin to .bashrc if needed
  src/api/IBMi.ts
  src/api/Storage.ts
Labels: enhancement

#1728 Correct all places where it was expected runCommand to crash
  src/api/CompileTools.ts
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/filesystems/qsys/extendedContent.ts
  src/languages/clle/clApi.ts
  src/languages/clle/getnewlibl.ts
  src/testing/action.ts
  src/views/objectBrowser.ts
Labels: bug

#1733 Fix error opening a specific member reference in Go To File
  src/instantiate.ts
Labels: bug
