Repository codefori/vscode-ibmi, pull requests merged in 2023-08, with the labels that each got.

#1477 Fix directory for shell check
  src/api/IBMi.ts
Labels: bug

#1482 Wrap paths to resolve with double quote
  src/api/IBMiContent.ts
  src/testing/content.ts
Labels: bug

#1460 Ability to create home directory
  CONTRIBUTING.md
  src/api/IBMi.ts
Labels: enhancement

#1145 Initial work for l10n - views
  package.json
  src/extension.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/locale/index.ts
  src/sandbox.ts
  src/views/ConnectionBrowser.ts
  src/views/LibraryListView.ts
  src/views/ProfilesView.ts
  src/views/helpView.ts
  src/views/ifsBrowser.js
  src/views/objectBrowser.js
  tsconfig.json
Labels: important

#1479 Add warning message if you're *ALLOBJ
  src/api/IBMi.ts
Labels: enhancement

#1433 Validate library list when connecting
  src/api/IBMi.ts
  src/api/Storage.ts
Labels: enhancement

#1485 Add missing `getEvfeventFiles` function
  src/api/errors/diagnostics.ts
  src/api/local/actions.ts
Labels: bug

#1489 Fix translations for Danish
  src/locale/ids/da.ts
Labels: bug

#1500 Fix ASP and library list validation
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/views/LibraryListView.ts
Labels: bug

#1503 Converted Object Browser and Filter Editor to TypeScript
  package-lock.json
  package.json
  src/api/Configuration.ts
  src/api/IBMiContent.ts
  src/api/Search.ts
  src/extension.ts
  src/filesystems/qsys/QSysFs.ts
  src/instantiate.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/views/objectBrowser.js
  src/views/objectBrowser.ts
  src/webviews/filters/index.js
  src/webviews/filters/index.ts
Labels: enhancement

#1505 Converted Actions Maintenance editor to TypeScript + added translations
  src/api/CustomUI.ts
  src/api/Tools.ts
  src/instantiate.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/webviews/actions/index.js
  src/webviews/actions/index.ts
  src/webviews/actions/varinfo.js
  src/webviews/actions/varinfo.ts
  src/webviews/variables/index.ts
Labels: enhancement
