Repository codefori/vscode-ibmi, pull requests merged in 2023-04, with the labels that each got.

#1123 Command Profiles
  package.json
  src/api/CompileTools.ts
  src/api/Configuration.ts
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/instantiate.ts
  src/languages/clle/getnewlibl.ts
  src/views/ProfilesView.ts
  src/webviews/commandProfile/index.ts
Labels: build

#1150 Add Quick Connect
  package.json
  src/api/Configuration.ts
  src/api/IBMi.ts
  src/api/Storage.ts
  src/views/ConnectionBrowser.ts
  src/webviews/login/index.ts
  src/webviews/settings/index.ts
Labels: enhancement

#1256 Fix stat on empty or specially named directories
  src/api/IBMiContent.ts
Labels: bug
