Repository codefori/vscode-ibmi, pull requests merged in 2024-05, with the labels that each got.

#2026 Initial work to remove joins from object list
  src/api/IBMiContent.ts
  src/api/Tools.ts
  src/api/local/deployTools.ts
  src/api/local/deployment.ts
  src/testing/action.ts
  src/testing/connection.ts
  src/testing/content.ts
  src/typings.ts
  src/views/objectBrowser.ts
Labels: bug

#2035 Put debugged program name in IBM i batch debug session
  src/api/debug/index.ts
Labels: enhancement

#2043 Add shortcut to search object and IFS browsers
  package.json
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: enhancement

#1975 Cleanup/connection_manager_api
  package.json
  src/api/Configuration.ts
  src/api/Tools.ts
  src/api/debug/index.ts
  src/extension.ts
  src/instantiate.ts
  src/sandbox.ts
  src/views/ConnectionBrowser.ts
  src/webviews/login/index.ts
  src/webviews/settings/index.ts
Labels: ready

#1985 Component API
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/Instance.ts
  src/api/Storage.ts
  src/api/Tools.ts
  src/components/component.ts
  src/components/copyToImport.ts
  src/components/getMemberInfo.ts
  src/components/getNewLibl.ts
  src/filesystems/qsys/extendedContent.ts
  src/instantiate.ts
  src/languages/clle/getnewlibl.ts
  src/languages/sql/getmbrinfo.ts
  src/testing/components.ts
  src/testing/content.ts
  src/testing/encoding.ts
  src/testing/index.ts
  src/typings.ts
  src/views/ProfilesView.ts
Labels: ready

#1907 Update editor tab on member rename
  src/api/Tools.ts
  src/locale/ids/da.json
  src/locale/ids/en.json
  src/locale/ids/fr.json
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: ready

#2079 Fix/project debug
  src/api/debug/index.ts
  src/api/local/env.ts
Labels: bug, build, debug

#2080 Fix types generation
  package.json
Labels: bug
