Repository codefori/vscode-ibmi, pull requests merged in 2024-02, with the labels that each got.

#1820 Display more explicit error message when connection fails
  src/api/IBMi.ts
Labels: enhancement

#1840 Fix context menu items wording in IFS browser
  package.json
Labels: enhancement

#1843 Move auto sort IFS shortcuts setting to Features tab
  src/webviews/settings/index.ts
Labels: bug

#1842 Fix removing (temp) IFS directories
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/local/deployment.ts
Labels: bug

#1839 Add option to show hidden files and directories in IFS browser
  package.json
  src/api/Configuration.ts
  src/views/ifsBrowser.ts
  src/webviews/settings/index.ts
Labels: enhancement

#1837 Stop letting the same document be opened twice
  src/api/Tools.ts
  src/api/errors/diagnostics.ts
  src/instantiate.ts
Labels: bug

#1845 Connection browser enhancements
  package.json
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/views/ConnectionBrowser.ts
  src/webviews/settings/index.ts
Labels: enhancement

#1850 Add tooltip for source files showing member count, source length and CCSID
  src/api/IBMiContent.ts
  src/api/Tools.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/views/LibraryListView.ts
  src/views/ProfilesView.ts
  src/views/helpView.ts
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: enhancement

#1851 Ignore error copying empty member
  src/views/objectBrowser.ts
Labels: bug

#1857 Allow dragging members to IFS directories
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: enhancement

#1859 Add concurrency level to postDownloads
  src/api/CompileTools.ts
Labels: build

#1852 Add object commands to sourcefiles in Object browser
  package.json
  src/typings.ts
  src/views/objectBrowser.ts
Labels: enhancement

#1871 Allow open members in object filters for *FILE
  src/api/IBMiContent.ts
Labels: enhancement

#1874 Fix error copying empty member
  src/views/objectBrowser.ts
Labels: bug

#1877 Tests and fix for library list order
  src/api/CompileTools.ts
  src/testing/connection.ts
Labels: build

#1880 Speed up library list loading when SQL is disabled
  src/api/IBMiContent.ts
Labels: enhancement

#1884 Allow multiple IFS files/folders download
  package.json
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/views/ifsBrowser.ts
Labels: enhancement
