Repository codefori/vscode-ibmi, pull requests merged in 2024-01, with the labels that each got.

#1756 Show recently opened files :boom:
  package.json
  src/api/Storage.ts
  src/instantiate.ts
Labels: enhancement

#1757 Feature/edit vs browse
  package.json
  src/api/Configuration.ts
  src/api/IBMiContent.ts
  src/instantiate.ts
  src/typings.ts
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
  src/views/searchView.ts
  src/webviews/settings/index.ts
Labels: enhancement

#1763 Escape path when testing streamfile for access rights
  src/api/IBMiContent.ts
Labels: bug

#1768 Fix path splitting when opening a member on an IASP
  src/api/IBMiContent.ts
  src/api/Tools.ts
  src/instantiate.ts
Labels: bug

#1771 Take in account for possible ASP in compile path
  src/api/errors/diagnostics.ts
Labels: bug, build

#1734 update vscode-test to @vscode/test-electron
  package-lock.json
  package.json
Labels: build

#1780 Enhance Object Browser filter's Object field
  package-lock.json
  package.json
  src/api/Configuration.ts
  src/api/Filter.ts
  src/api/IBMiContent.ts
  src/api/Tools.ts
  src/sandbox.ts
  src/testing/content.ts
  src/testing/filter.ts
  src/testing/index.ts
  src/typings.ts
  src/views/objectBrowser.ts
  src/webviews/filters/index.ts
Labels: enhancement

#1810 Add missing property on filter objects
  src/api/local/git.ts
Labels: bug
