Repository codefori/vscode-ibmi, pull requests merged in 2024-07, with the labels that each got.

#2148 Added simple hostname to debug certificate subjectAltName
  src/api/debug/certificates.ts
Labels: bug, debug

#2142 Fix `countFiles` when directory does not exist
  src/api/IBMiContent.ts
  src/testing/connection.ts
Labels: ready

#2146 Use default open mode in IFS search and find results
  src/instantiate.ts
  src/views/searchView.ts
Labels: bug

#2155 Add Save password button on password prompt
  src/api/IBMi.ts
  src/locale/ids/fr.json
  src/webviews/login/index.ts
Labels: enhancement

#2154 Await on event subscribers functions
  src/api/IBMi.ts
  src/api/Instance.ts
Labels: bug

#2157 Always debug securely
  package.json
  src/api/Configuration.ts
  src/api/debug/index.ts
  src/views/debugView.ts
  src/webviews/settings/index.ts
Labels: enhancement, debug

#2163 Add `Download Logs` option to Help and Support view
  package-lock.json
  package.json
  src/api/IBMi.ts
  src/locale/ids/da.json
  src/locale/ids/de.json
  src/locale/ids/en.json
  src/locale/ids/fr.json
  src/locale/ids/no.json
  src/locale/ids/pl.json
  src/views/helpView.ts
  webpack.config.js
Labels: enhancement

#2182 Fix event functions chain crash
  package-lock.json
  package.json
  src/api/Instance.ts
  src/api/Terminal.ts
  src/api/debug/index.ts
  src/api/local/deployment.ts
  src/extension.ts
  src/filesystems/qsys/QSysFs.ts
  src/instantiate.ts
  src/testing/index.ts
  src/views/ConnectionBrowser.ts
  src/views/LibraryListView.ts
  src/views/debugView.ts
  src/views/helpView.ts
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: bug
