Repository codefori/vscode-ibmi, pull requests merged in 2024-09, with the labels that each got.

#2238 Fix error when dragging to IFS directory with special characters
  src/views/ifsBrowser.ts
Labels: bug, ready

#2263 Upgrade deprecated `actions/upload-artifact@v2` to `v4`
  .github/workflows/pr.yaml
Labels: build

#2060 Allow Save As and breadcrumb navigation
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/Tools.ts
  src/filesystems/ifsFs.ts
  src/filesystems/qsys/QSysFs.ts
  src/testing/connection.ts
  src/testing/content.ts
  src/testing/tools.ts
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: enhancement
