Repository codefori/vscode-ibmi, pull requests merged in 2024-08, with the labels that each got.

#2213 Fix `Search Source File` crashing when used with a complex filter
  src/api/IBMi.ts
  src/api/Search.ts
  src/api/Storage.ts
  src/testing/index.ts
  src/testing/search.ts
  src/views/objectBrowser.ts
  src/views/searchView.ts
Labels: bug

#2215 Fixed object/members listing failing when name contains variant chars
  src/api/IBMiContent.ts
  src/testing/content.ts
Labels: bug

#2224 Add action to open location after download of members/streamfiles
  src/locale/ids/de.json
  src/locale/ids/en.json
  src/locale/ids/fr.json
  src/locale/ids/no.json
  src/locale/ids/pl.json
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: enhancement

#2221 Fixed IFS commands/methods crashing with paths with blanks
  src/api/IBMiContent.ts
  src/api/Terminal.ts
Labels: bug

#2227 Add additional checks for debug configuration/certificate
  src/api/debug/certificates.ts
  src/api/debug/config.ts
  src/api/debug/index.ts
  src/locale/ids/en.json
  src/views/debugView.ts
Labels: enhancement, debug

#2231 Change logic for triggering disconnect
  src/api/IBMi.ts
Labels: bug
