Repository codefori/vscode-ibmi, pull requests merged in 2024-03, with the labels that each got.

#1888 Allow multi members download
  package.json
  src/api/IBMi.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/testing/connection.ts
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: enhancement

#1905 'Add to library list' and 'Set as current library' actions on browsers items
  package.json
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/views/LibraryListView.ts
  src/views/objectBrowser.ts
Labels: enhancement

#1906 Don't show context sensitive commands in Command Palette
  package.json
Labels: bug

#1916 Fixed file extension when downloading a single IFS file
  src/views/ifsBrowser.ts
Labels: bug

#1928 Fixed drag crashing for streamfiles
  src/views/ifsBrowser.ts
  src/views/objectBrowser.ts
Labels: bug

#1890 Change secrets API
  src/api/Storage.ts
  src/instantiate.ts
  src/testing/index.ts
  src/testing/storage.ts
  src/webviews/settings/index.ts
Labels: enhancement, build

#1895 Changes/debugger_certs
  package.json
  src/api/Configuration.ts
  src/api/IBMi.ts
  src/api/debug/certificates.ts
  src/api/debug/index.ts
  src/api/debug/server.ts
Labels: enhancement

#1940 Correctly handle source members with variant characters in their name
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/Tools.ts
Labels: bug

#1941 Replace all toUpperCase whith IBMi.upperCaseName where relevant
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/debug/index.ts
  src/filesystems/qsys/QSysFs.ts
  src/filesystems/qsys/extendedContent.ts
  src/instantiate.ts
  src/testing/connection.ts
  src/testing/content.ts
  src/views/LibraryListView.ts
  src/views/objectBrowser.ts
  src/webviews/filters/index.ts
  src/webviews/settings/index.ts
Labels: bug
