Repository codefori/vscode-ibmi, pull requests merged in 2024-04, with the labels that each got.

#1960 Use interfaces instead of classes for type checking
  src/views/objectBrowser.ts
Labels: bug

#1962 Added support for .deployignore
  src/api/local/deployTools.ts
  src/testing/deployTools.ts
  src/views/ifsBrowser.ts
Labels: enhancement

#1949 Fix member and object resolve with variants
  src/api/IBMiContent.ts
  src/testing/content.ts
Labels: bug, ready

#1923 SEP support
  package.json
  src/api/Configuration.ts
  src/api/debug/certificates.ts
  src/api/debug/index.ts
  src/api/debug/server.ts
  src/webviews/settings/index.ts
Labels: ready

#1969 Change library validation logic
  src/api/IBMiContent.ts
  src/testing/content.ts
Labels: ready

#1986 CompletionItemProvider for local actions variables
  package.json
  schemas/local-variables.code-snippets
  src/extension.ts
  src/languages/actions/completion.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
Labels: enhancement

#1968 Major API cleanup
  package.json
  src/api/Configuration.ts
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/Search.ts
  src/api/Storage.ts
  src/filesystems/qsys/QSysFs.ts
  src/instantiate.ts
  src/testing/content.ts
  src/testing/encoding.ts
  src/testing/index.ts
  src/typings.ts
  src/views/helpView.ts
  src/views/objectBrowser.ts
  src/webviews/settings/index.ts
Labels: ready

#1989 Do not allow debug batch on *SRVPGM / Allow multiple debug sessions
  package.json
  src/api/debug/index.ts
Labels: enhancement

#1976 Fallback to system resolve if error file path not relative
  src/api/errors/diagnostics.ts
Labels: bug

#1867 Speed up logic to validate member and extension exists
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/instantiate.ts
  src/languages/sql/getmbrinfo.ts
  src/testing/content.ts
Labels: enhancement, ready

#1996 Fix/debug_version_path
  package.json
  src/api/debug/server.ts
Labels: bug

#1990 Debug service configuration and management improvement
  package.json
  src/api/Configuration.ts
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/Storage.ts
  src/api/debug/certificates.ts
  src/api/debug/config.ts
  src/api/debug/index.ts
  src/api/debug/server.ts
  src/instantiate.ts
  src/locale/ids/da.ts
  src/locale/ids/en.ts
  src/locale/ids/fr.ts
  src/typings.ts
  src/views/debugView.ts
  src/webviews/settings/index.ts
Labels: enhancement

#2005 Hide the connection browser when connecting
  package.json
  src/api/IBMi.ts
Labels: enhancement

#2015 Set CCSID of deployed files to 1208 if needed
  src/api/local/deployment.ts
Labels: enhancement
