Repository codefori/vscode-ibmi, pull requests merged in 2025-06, with the labels that each got.

#2713 Fix/cqsh path
  CONTRIBUTING.md
  webpack.config.js
Labels: bug

#2687 Complete actions schema
  schemas/actions.json
  src/languages/actions/completion.ts
  src/ui/actions.ts
Labels: enhancement

#2703 Run `cp` and `mv` in QSH to keep CCSID attribute
  src/api/IBMiContent.ts
  src/api/tests/suites/content.test.ts
  src/ui/views/ifsBrowser.ts
Labels: bug

#2714 Throw an error and abort build when file to copy is not found
  webpack.config.js
Labels: javascript

#2715 Enable drag and drop support in library list view
  package.json
  src/api/types.ts
  src/extension.ts
  src/ui/views/LibraryListView.ts
  src/ui/views/ifsBrowser.ts
  src/ui/views/objectBrowser.ts
Labels: enhancement

#2742 Fixed tests to run on CCSID 297 and iasps + fixed getMemberInfo for CCSID 297
  .github/workflows/test.yaml
  src/api/.env.sample
  src/api/IBMi.ts
  src/api/IBMiContent.ts
  src/api/components/getMemberInfo.ts
  src/api/tests/connection.ts
  src/api/tests/setup.ts
  src/api/tests/suites/asp.test.ts
  src/api/tests/suites/components.test.ts
  src/api/tests/suites/connection.test.ts
  src/api/tests/suites/content.test.ts
  src/api/tests/suites/encoding.test.ts
  src/api/tests/suites/search.test.ts
  src/api/tests/suites/variables.test.ts
  src/api/tests/testConfigSetup.ts
  vitest.config.ts
Labels: bug
