Repository codefori/vscode-ibmi, pull requests merged in 2025-01, with the labels that each got.

#2443 New connection settings `Connection Timeout` field
  package-lock.json
  package.json
  src/api/CustomUI.ts
  src/api/IBMi.ts
  src/typings.ts
  src/webviews/login/index.ts
  src/webviews/settings/index.ts
Labels: enhancement

#2437 Correctly check GetNewLibl component state
  src/api/IBMi.ts
  src/components/getMemberInfo.ts
  src/components/getNewLibl.ts
Labels: bug

#2480 Replace hardcoded 'diff' command with constant
  src/commands/compare.ts
Labels: bug

#2481 Enhance runCommand with error handling and event callbacks
  src/api/CompileTools.ts
  src/api/tests/suites/connection.test.ts
  src/ui/actions.ts
Labels: bug

#2479 Fix #2478: Delete docs folder
  CONTRIBUTING.md
  docs/index.html
Labels: documentation
