Repository codefori/vscode-ibmi, pull requests merged in 2025-03, with the labels that each got.

#2526 Mass source download fails on zero record members #2513
  src/ui/views/objectBrowser.ts
Labels: bug

#2571 Fix failed IFS download notification
  src/ui/views/ifsBrowser.ts
Labels: bug

#2552 Better authority check when starting Debug Service
  src/debug/server.ts
Labels: enhancement, debug

#2587 Fixed droping QSYS members into IFS folder
  src/ui/views/ifsBrowser.ts
  src/ui/views/objectBrowser.ts
Labels: bug

#2589 Added Compare with each other command
  package.json
  src/commands/compare.ts
  src/instantiate.ts
Labels: enhancement
